version: '2'
services:
  web:
    image: nginx:1.11-alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./inf/dev/web/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
  app:
    image: 1maa/php-fpm:7.0-xdebug
    depends_on:
      - db
      - kvs
    ports:
      - "4444:22"
    volumes:
      - .:/var/www/docker-symfony.dev
    working_dir: /var/www/docker-symfony.dev
  db:
    image: 1maa/postgres-dev:9.5
    volumes:
      - db_data:/var/lib/postgres/9.5
  kvs:
    image: redis:3.2-alpine
    volumes:
      - kvs_data:/data
volumes:
  db_data: ~
  kvs_data: ~
